---
- name: Launch EC2 Instances
  hosts: localhost
  gather_facts: no  # Disable gathering facts since this play doesn't need them

  tasks:
    - name: Launch First EC2 Instance
      ec2:
        key_name: demo_key
        instance_type: t2.micro
        image: ami-053b0d53c279acc90
        wait: yes
        region: us-east-1
        vpc_subnet_id: subnet-0bf916f334dd8e482
        instance_tags:
          Name: First

    - name: Launch Second EC2 Instance
      ec2:
        key_name: demo_key
        instance_type: t2.micro
        image: ami-053b0d53c279acc90
        wait: yes
        region: us-east-1
        vpc_subnet_id: subnet-0faabdddd7ca09550
        instance_tags:
          Name: Second
