---
- name: Ansible with AWS
  hosts: localhost

  vars:
      region: us-east-1
      instance_type: t2.micro
      ami: ami-053b0d53c279acc90 
      keypair: my_keypair
      subnetid: subnet-0bf916f334dd8e482
      # hostpath: ./hosts
      # hoststring: "ansible_ssh_user=ubuntu ansible_ssh_private_key_file=/home/ubuntu/.ssh/managedkey"
      
  tasks:
    - ec2_key:
        region: "{{ region }}"
        name: my_keypair
        key_material: "{{ lookup('file', '/home/ubuntu/ansibleWithJenkins/managedkey.pub') }}"
    - name: Create an ec2 instance
      ec2:
        key_name: "{{ keypair }}"
        group: default  # security group name
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        wait: true
        region: "{{ region }}"
        exact_count: 1 # default
        count_tag:
          Name: "{{ item.hostname }}"
        vpc_subnet_id: "{{ subnetid }}"
        assign_public_ip: yes
      register: ec2
      with_items:
        - hostname: roll1
        - hostname: roll2

    # - name: Add the newly created EC2 instance(s) to host group
    #   lineinfile: dest={{ hostpath }}
    #               regexp={{ item.public_ip }} 
    #               insertafter="localhost" 
    #               line="{{ item.public_ip }} {{hoststring}}"
    #               state=present
    #   with_items: "{{ec2.instances}}"

    # - wait_for: path={{ hostpath }} search_regex={{hoststring}}

    # - name: Wait for SSH to come up
    #   local_action: wait_for 
    #                 host={{ item.public_ip }} 
    #                 port=22 
    #                 state=started
    #   with_items: "{{ec2.instances}}"

    # - name: Add IP to ec2_hosts group
    #   add_host: hostname={{ item.public_ip }} groups=ec2_hosts
    #   with_items: "{{ec2.instances}}"