---
- hosts: all
  gather_facts: false
  vars:
      region: us-east-1
      instance_type: t2.micro
      ami: ami-053b0d53c279acc90 
      keypair: my_keypair
      subnetid: subnet-0bf916f334dd8e482
  tasks:
    - ec2_key:
        region: "{{ region }}"
        name: my_keypair
        key_material: "{{ lookup('file', '/home/ubuntu/managedkey.pub') }}"
    - ec2:
        key_name: "{{ keypair }}"
        group: default  # security group name
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        wait: true
        region: "{{ region }}"
        exact_count: 1 # default
        count_tag:
          Name: "{{ item.hostname }}"
        vpc_subnet_id: "{{ subnetid }}"
        assign_public_ip: yes
      register: ec2
      with_items:
        - hostname: roll1
        - hostname: roll2
    - apt: name=nginx state=latest
    - service:
          name: nginx
          state: started