---
- hosts: localhost
  gather_facts: false
  become: true
  vars:
      region: us-east-1
      instance_type: t2.micro
      ami: ami-053b0d53c279acc90
      keypair: my_keypair
      subnetid: subnet-0bf916f334dd8e482
  tasks:
    - ec2_key:
        region: "{{ region }}"
        name: my_keypair
        key_material: "{{ lookup('file', '/home/ubuntu/managedkey.pub') }}"
    - ec2_instance:
        key_name: "{{ keypair }}"
        name: "webserver"
        security_group: default  # security group name
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami }}"
        wait: true
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnetid }}"
        count: 2 # default
        network:
          assign_public_ip: true