---
- hosts: tag_Name_webserver
  become: true
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: latest
    
    - name: Webpage
      copy:
        content: "<h1> WebPage of Ansible-Slave node Whose Privateip is {{ ansible_facts['default_ipv4']['address'] }} and public_ip is {{ inventory_hostname }} </h1>"
        dest: "/var/www/html/index.html"